# Generated by Django 5.2.4 on 2025-07-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место выполнения действия", max_length=255
                    ),
                ),
                ("time", models.TimeField(help_text="Время выполнения действия")),
                (
                    "action",
                    models.CharField(help_text="Описание действия", max_length=255),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(default=False, help_text="Приятная привычка"),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Периодичность выполнения в днях (не реже 1 раза в 7 дней)",
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        help_text="Время выполнения в секундах (максимум 120 секунд)"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Связанная привычка",
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_to",
                        to="habits.habit",
                    ),
                ),
            ],
        ),
    ]
